#!/bin/bash
factom-cli setup loadtest          # Which may or may not create the fountain addresses
factom-cli newaddress ec app
factom-cli newtransaction lt
factom-cli addinput       lt 07-Fountain 1000
factom-cli addecoutput    lt app 1000
factom-cli addfee         lt 07-Fountain
factom-cli sign           lt
factom-cli submit         lt
echo "We are going to sleep for a while to let the client sync with the server" 
sleep 10
echo 1
sleep 10
echo 2
sleep 10
echo 3
sleep 10
echo 4
sleep 10
echo 5
sleep 10
echo 6
sleep 10
factom-cli balances


rand=$(openssl rand -base64 8)
chainid=$(echo testing | factom-cli mkchain -e $rand -e test app | awk -F': ' '{print $2}')

echo ChainID: $chainid >>testchainid

for ((i=0; i < 1000; i++)); do
        echo $i | factom-cli put -c $chainid -e $i app &
        sleep 1
done

